name: medical_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.8
  cached_network_image: ^3.3.0
  syncfusion_flutter_gauges: ^24.1.46
  photo_view: ^0.14.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  get: ^4.6.6
  provider: ^6.0.5
  easy_localization: ^3.0.3
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.4

  flutter_plugin_android_lifecycle: ^2.0.6
  win32: 2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo1.jpg"
  min_sdk_android: 19

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/translation/
    - assets/temp/
    - assets/logo/
    - assets/test/
    - assets/